server:
  port: 8085
spring:
  application:
    name: cloud-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
# 开启feign的hystrix
feign:
  hystrix:
    enabled: true

# 更改ribbon负载均衡策略
eureka-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

# com.netflix.loadbalancer.RandomRule #配置规则 随机
# com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
# com.netflix.loadbalancer.RetryRule #配置规则 重试
# com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
# com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略

# HystrixDashboard路由
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
